### ISSUE TITLE
Not able to resolve Find and Replace texts with dash "-"

### ISSUE THREAD

**Issue by DiwakarXT** [Sven-Bo/python-word-automation#2]
If you are trying to Find a Text "AB-1234" from excel and replace with a corresponding value, the following error msg is shown

ERROR MSG:

jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'integer'

**Comment by Sven-Bo** [comment]
I tested it. Works without any issue with "AB-1234". Screenshot:
https://www.screencast.com/t/btzhcy50f

**Comment by DiwakarXT** [comment]
Hi Sven, thank you for testing it for me. Can you please check if it works on the First column where "-" is part of the placeholder column texts? Thank you again!

**Comment by Sven-Bo** [comment]
Hey @DiwakarXT,

Sorry to say, but I'm pretty busy right now and don't have time to test the code for you. To get some help, it would be great if you could **share a minimal reproducible** code and **the exact error message** you're getting.

Hope you can understand, thanks!
